# Generated by Django 5.0.7 on 2024-07-23 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_handler_two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('public_key_path', models.CharField(max_length=255)),
                ('encrypted_sym_key_path', models.CharField(max_length=255)),
                ('encrypted_iv_path', models.CharField(max_length=255)),
                ('encrypted_file_path', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.account')),
            ],
        ),
    ]
