# Generated by Django 5.0.7 on 2024-07-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_file_handler_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_handler_two',
            name='tag_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
