# Generated by Django 5.0.7 on 2024-07-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_file_handler_two_encrypted_iv_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_handler_two',
            name='fernetkeyl1',
        ),
        migrations.RemoveField(
            model_name='file_handler_two',
            name='fernetkeyl2',
        ),
    ]
